// SPDX-License-Identifier: MIT

pragma solidity ^0.8.24;

import {Script} from "forge-std/Script.sol";
import {console} from "forge-std/console.sol";


/**
 * @notice Generates the JSON input file used to construct the Merkle tree. 
 * @author Legendarycode
 * 
 * @dev 
 *      The script creates a list of whitelisted addresses and assigns the same
 *      token allocation to each address. It then serializes the data into the
 *      JSON structure expected by the `MakeMerkle` script and writes the result
 *      to `script/target/input.json`.
 * 
 *      The generated JSON contains:
 *      - The data types used by each claim.
 *      - The total number of claims.
 *      - The address and token amount for each claim.
 */
contract GenerateInput is Script {

    /// @notice Location of the JSON file generated by this script.
    string constant FILE_PATH = "script/target/input.json";


    /// @notice Generates the Merkle input data and writes it to the target JSON file.
    function run() external {

         // Define the data types used to construct each Merkle leaf.
        string[] memory types = new string[](2);
        types[0] = "address";
        types[1] = "uint";

        /// @notice Token allocation assigned to each whitelisted address.
        uint256 amount = 25 * 1e18;

        // Define the addresses eligible to receive the airdrop.
        address[] memory whitelist = new address[](4);

        whitelist[0] = 0x6CA6d1e2D5347Bfab1d91e883F1915560e09129D;
        whitelist[1] = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
        whitelist[2] = 0x0c8Ca207e27a1a8224D1b602bf856479b03319e7;
        whitelist[3] = 0xf6dBa02C01AF48Cf926579F77C9f874Ca640D91D;

        // Convert the claim data into the JSON format expected by MakeMerkle.
        string memory json = createJSON(types, whitelist, amount);

        // Write the generated JSON data to the configured output path.
        vm.writeFile(FILE_PATH, json);

        console.log("Successfully wrote input.json to %s", FILE_PATH);
    }


    /**
     * @notice Constructs the JSON representation of the Merkle tree input data.
     * 
     * @dev
     *      The generated structure contains the claim types, total claim count,
     *      and indexed claim values. Each claim consists of an address and its
     *      corresponding token allocation.
     * 
     * @param types Data types used by each claim.
     * @param whitelist Addresses eligible for the airdrop.
     * @param amount Token allocation assigned to each address.
     * @return json JSON-formatted Merkle tree input data.
     */
    function createJSON(
        string[] memory types,
        address[] memory whitelist,
        uint256 amount
    ) internal pure returns (string memory) {
        string memory json = "{";

        // Serialize the claim data types into the JSON `types` array.
        json = string.concat(json, "\"types\": [");

        for (uint256 i = 0; i < types.length; i++) {
            json = string.concat(json, "\"", types[i], "\"");

            if (i < types.length - 1) {
                json = string.concat(json, ", ");
            }
        }

        json = string.concat(json, "], ");

        // Store the number of claims so MakeMerkle knows how many entries to process.
        json = string.concat(
            json,
            "\"count\": ",
            vm.toString(whitelist.length),
            ", "
        );

        // Begin serializing the indexed claim values.
        json = string.concat(json, "\"values\": {");

        for (uint256 i = 0; i < whitelist.length; i++) {
            json = string.concat(
                json,
                "\"",
                vm.toString(i),
                "\": {",
                "\"0\": \"",
                vm.toString(whitelist[i]),
                "\", ",
                "\"1\": \"",
                vm.toString(amount),
                "\"}"
            );

            if (i < whitelist.length - 1) {
                json = string.concat(json, ", ");
            }
        }

         // Close the `values` object and the root JSON object.
        json = string.concat(json, "}}");

        return json;
    }
}